default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: tweet_development

test:
  <<: *default
  database: tweet_test

production:
  <<: *default
  database: tweet_production
  username: tweet
  password: <%= ENV['TWEET_DATABASE_PASSWORD'] %>
